language: python
python:
  - 2.7
  - 3.4
services:
  - postgresql
install:
  - pip install -r requirements.txt
before_script:
  - python manage.py syncdb --migrate --noinput
  - psql -U postgres -c 'CREATE DATABASE "cdzforever";'
script:
  - python manage.py test
