language: python
python:
  - 2.7
  - 3.4
env:
  global:
    - DATABASE_URL=postgres://postgres@localhost/travis_ci_test
    - SECRET_KEY=s3cr3t_k3y_l0l
    - DEBUG=1
services:
  - postgresql
install:
  - pip install -r requirements.txt
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - python manage.py syncdb --migrate --noinput
script:
  - python manage.py test
